# ===================================================================
# Spring Boot configuration for the "mysql" profile.
#
# ===================================================================


spring:

    datasource:
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource # com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dev_nixmashspring?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: admin
        password: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        hibernate:
            ddl-auto: update # DDL mode (none, validate, update, create, create-drop), shortcut for the "hibernate.hbm2ddl.auto" property.
        properties:
            hibernate:
                #dialect: org.hibernate.dialect.H2Dialect
                connection.charSet: UTF-8
                hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor