


---



    jpa:
        show-sql: true # Enable logging of SQL statements.
        properties:
             hibernate.cache.use_second_level_cache: true
             hibernate.cache.use_query_cache: false
             hibernate.generate_statistics: true
             hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
             #hibernate.connection.charSet: UTF-8
             #hibernate.characterEncoding: UTF-8
             #hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

---

spring:
    # H2 Profiles
    # ===============================================================
    profiles: h2

    datasource:
        url: jdbc:h2:mem:mixtash;DB_CLOSE_DELAY=-1
        # driver-class-name: org.h2.Driver
        username: mixtash
        password:

    h2:
        console:
            enabled: false
    jpa:
        database: H2
        database-platform: org.hibernate.dialect.H2Dialect
        #hibernate.ddl-auto: create-drop # default value

---

spring:
    # Mysql Profiles
    # ===============================================================
    profiles: mysql

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dev_nixmashspring?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: admin
        password: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        hibernate:
            ddl-auto: update # DDL mode (none, validate, update, create, create-drop), shortcut for the "hibernate.hbm2ddl.auto" property.
        properties:
            hibernate:
                #dialect: org.hibernate.dialect.H2Dialect
                connection.charSet: UTF-8
                hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

---


# ===================================================================
# Hibernate HBM2DDL Setting
# ===================================================================
# "create"      - to build a new database on each run;
# "update"      - to modify an existing database;
# "create-drop" - means the same as "create" but also drops tables when Hibernate closes;
# "validate"    - makes no changes to the database
# ===================================================================




# ===================================================================
# NixMash external properties
# ===================================================================
# TODO : move in a external file

external:
    isDemoSite: true #  disabling the Registration Form button if true
    # FACEBOOK
    facebookAppId: sdsdsds
    facebookAppSecret: sdsdsdsds
    # TWITTER
    twitterAppId: sdsdsds
    twitterAppSecret: sdsdsdsds

    # not present
    #siteName: My Site

    googleAppId: sdsdsdsds
    googleAppSecret: sdsdsds
    googleMapKey: dfdfdfd

    profileImagePath: /websites/yoursite/files/users/avatars/
    profileImageUrlRoot: /files/users/avatars/
    profileIconPath: /websites/yoursite/files/users/icons/
    profileIconUrlRoot: /files/users/icons/

    #googleAnalyticsTrackingId: 12345
    #addGoogleAnalytics: false

    editorImagePlacemarker: http://yoursite.com/files/images/placemarker.png

    baseUrl: http://yoursite.com
    rssChannelTitle: RSS Channel Title
    rssChannelDescription: RSS Channel Description

