# Custom properties for field value
# Packages
package.root: com.nixmash.springdata.solr

#spring:
 #   profiles.active: dev

---

spring:
    # PROFILES
    profiles: dev
    # Solr Properties bind with FILE DEFINED in Solr/Common/NixmashSolrProperties.java
nixmashsolr.solrServerUrl= http://localhost:8983/solr/#/collection2
nixmashsolr.solrEmbeddedPath= C:\DevLabs\Workspace-mars\Spring-NixMash\install\solr\embedded
---

spring:
    # PROFILES
    profiles: prod
    # Solr Properties bind with FILE DEFINED in Solr/Common/NixmashSolrProperties.java
nixmashsolr:
    solrServerUrl: http://localhost:8983/solr/#/collection3
    solrEmbeddedPath: C:\DevLabs\Workspace-mars\Spring-NixMash\install\solr\embedded

---








