# Custom properties for field value
# Packages
package.root: com.nixmash.springdata.solr

spring:
    profiles.active: dev

---

spring:
    # PROFILES
    profiles: dev
    # Solr Properties bind with FILE DEFINED in Solr/Common/NixmashSolrProperties.java
nixmashsolr:
    solrServerUrl: http://localhost:8983/solr/#/collection1
    solrEmbeddedPath: C:\DevLabs\Workspace-mars\Spring-NixMash\install\solr\embedded
---

spring:
    # PROFILES
    profiles: prod
    # Solr Properties bind with FILE DEFINED in Solr/Common/NixmashSolrProperties.java
nixmashsolr:
    solrServerUrl: http://localhost:8983/solr/#/collection1
    solrEmbeddedPath: C:\DevLabs\Workspace-mars\Spring-NixMash\install\solr\embedded

---

# Default spring BOOT sorlServer Properties
#spring:
#    data:
#        solr:
#            host: http://127.0.0.1:8983/solr # Solr host. Ignored if "zk-host" is set.
#            repositories.enabled: true # Enable Solr repositories.
#            zk-host: # ZooKeeper host address in the form HOST:PORT.


# Default spring BOOT sorlServer Properties
#spring:
#    data:
#        solr:
#            host: http://127.0.0.1:8983/solr # Solr host. Ignored if "zk-host" is set.
#            repositories.enabled: true # Enable Solr repositories.
#            zk-host: # ZooKeeper host address in the form HOST:PORT.






