# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        include: mysql # automatically set the given profile
    devtools:
        restart:
            enabled: false
        livereload:
            enable: false
    messages:
            cache-seconds: 1
    thymeleaf:
            cache: false


# ===================================================================
# LOGGING
# ===================================================================

logging:
    #file: logs/dev_app.log
    pattern:
        console: "%d %.-5level|JPA|%-30.30logger{0}|%msg%n" # date , Level en 5 lettre max, classe du log , message
        #file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        ROOT: WARN
        com.nixmash.springdata: INFO
        org.springframework: WARN
        org.springframework.web: WARN
        org.springframework.security: WARN
        org.springframework.cache: WARN
        javax.activation: WARN
        javax.mail: WARN
        javax.xml.bind : WARN
        ch.qos.logback : WARN
        com.codahale.metrics : WARN
        com.ryantenney : WARN
        com.zaxxer : WARN  # <!--HicariCP Pool log-->
        net.sf.ehcache : WARN
        org.apache : WARN
        org.apache.catalina.startup.DigesterFactory : OFF
        org.hibernate : WARN
        org.hibernate.validator : WARN
        org.hibernate.ejb.HibernatePersistenceProvider : OFF
        org.thymeleaf: WARN

# ===================================================================
# NixMash specific properties
# ===================================================================


nixmash:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: demo2
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
